name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions Dependencies
        run: |
          cd functions
          npm install

      - name: Save Firebase Service Account Key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${{ github.workspace }}/firebase-service-account.json

      - name: Set up Firebase Authentication
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/firebase-service-account.json"

      - name: Deploy to Firebase Hosting Preview
        if: github.event_name == 'pull_request' && github.base_ref == 'preview'
        run: |
          firebase use --project black-market-129be
          firebase deploy --only hosting --channel=preview --project black-market-129be --message "Deploying preview"

      - name: Deploy to Firebase Hosting Live
        if: github.ref == 'refs/heads/main'
        run: |
          firebase use --project black-market-129be
          firebase deploy --only hosting --project black-market-129be --message "Deploying live"
